### ISSUE TITLE
Kilka usprawnień

### ISSUE THREAD

**Issue by pniedzwiedzinski** [zsk-poznan/szczesliwy-numerek-backend#1]
Jako że to jest web scraper to to jest mega niestabilne - serwery vulcana lubią wariować. Dlatego jak robiłem `get-lucky` to tam wprowadziłem kilka "usprawnień", które miały pomóc przy reagowaniu na awarię systemu.

## Data parsowania

http://get-lucky.netlify.com/.netlify/functions/get
Przy API get-lucky dodałem pole `date`, w które wpisywałem date parsowania numerka. Dzięki temu "klienty" czy inne aplikacje z tego api korzystające mogły w razie czego same sprawdzić czy nie było żadnego errora.

## Numerki w dni wolne

W dni wolne numerek nie jest generowany. Głupio by było żebyśmy my trzymali jakiś numerek. Moją taktyką na dni wolne było wstawianie po prostu `0`.

(0 - bo początkowo get-lucky powstało dla naszego klasowego bota co wysyła numerki i dzięki temu mogłem rozpoznać kiedy jest wolne)
http://get-lucky.netlify.com/.netlify/functions/get

## :wink: 
Te dwie rzeczy uważam że są nice to have, więc jak ktoś chce tutaj pomóc czy coś to można zrobić.

**Comment by kvpsky** [comment]
Dobry pomysł, wprowadzę zmiany Soon™
